@startuml

entity PrefCodes {
	id [int]
	name [text]
}

entity CityCodes {
	id [int]
	name [text]
}

entity Categories {
	id [int]
	name [text]
}

entity Entities {
    id [int]
    name [text]
    desc [text]
    picture [text]
    category_id [int]
    ----
    geo [geometry]
    pref_id [int]
    city_id [int]
}

entity ZooData {
    id [int]
    entity_id [int]
    map [text]
    open_time [time]
    close_time [time]
}

entity ZooEvents {
	id [int]
	zoo_id [int]
	name [text]
	desc [text]
	---
	location [text]
	start_time [date]
	end_time [date]
}

entity TempleData {
    id [int]
    entity_id [int]
    deity [text]
    luck [text]
    history [text]
}

Entities --{ TempleData
Entities --{ ZooData
ZooData -{ ZooEvents

PrefCodes --{ Entities
CityCodes --{ Entities
Categories --{ Entities

@enduml
