@startuml

entity PrefCodes {
	id [int]
	name [text]
}

entity CityCodes {
	id [int]
	name [text]
}

entity Categories {
	id [int]
	name [string]
}

entity ZooEvents {
	id
	zoo_id
	name
	description
	---
	location
	start_time
	end_time
}

entity Entities {
    id
    name
    description
    picture
    categoryId
    ----
    geo
    pref
    city
}

entity TempleData {
    id
    entityId
    deity
    luck
    history
}

entity ZooData {
    id
    entityId
    map
    open_time
    clone_time
}

Entities --{ TempleData
Entities --{ ZooData
ZooData -{ ZooEvents

PrefCodes --{ Entities
CityCodes --{ Entities
Categories --{ Entities

@enduml
